### ISSUE TITLE
Unzip error

### ISSUE THREAD

**Issue by Racater** [leinardi/JDInstaller#31]
Hello and thanks for the amazing script. While running it on a new Ubuntu 24.04 installation, the following error appeared. Unzip is installed. How can I fix it?

> TASK [davinci_resolve : Unzip downloaded archive] **************************************************************************************************************************************
> fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to find handler for \"/tmp/DaVinci_Resolve_19.1.3.zip\". Make sure the required command to extract the file is installed.\nCommand \"/usr/bin/tar\" could not handle archive: Unable to list files in the archive: zstd: /*stdin*\\: unsupported format \n/usr/bin/tar: Child returned status 1\n/usr/bin/tar: Error is not recoverable: exiting now\n\nCommand \"/usr/bin/tar\" could not handle archive: Unable to list files in the archive: /usr/bin/tar: This does not look like a tar archive\n/usr/bin/tar: Skipping to next header\n/usr/bin/tar: Exiting with failure status due to previous errors\n\nCommand \"/usr/bin/tar\" could not handle archive: Unable to list files in the archive: bzip2: (stdin) is not a bzip2 file.\n/usr/bin/tar: Child returned status 2\n/usr/bin/tar: Error is not recoverable: exiting now\n\nCommand \"/usr/bin/unzip\" could not handle archive:   End-of-central-directory signature not found.  Either this file is not\n  a zipfile, or it constitutes one disk of a multi-part archive.  In the\n  latter case the central directory and zipfile comment will be found on\n  the last disk(s) of this archive.\nunzip:  cannot find zipfile directory in one of /tmp/DaVinci_Resolve_19.1.3.zip or\n        /tmp/DaVinci_Resolve_19.1.3.zip.zip, and cannot find /tmp/DaVinci_Resolve_19.1.3.zip.ZIP, period.\n\nCommand \"/usr/bin/tar\" could not handle archive: Unable to list files in the archive: xz: (stdin): File format not recognized\n/usr/bin/tar: Child returned status 1\n/usr/bin/tar: Error is not recoverable: exiting now\n"}
> 
> PLAY RECAP *****************************************************************************************************************************************************************************
> localhost                  : ok=21   changed=5    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0   
> 
>

**Comment by Mohido** [comment]
I think it is crying because for somereason, `.ZIP` was appended to the name. The easiest fix I think is to go to your `/tmp/DaVinci_Resolve_19.1.3.zip.ZIP` and rename it (remove the last .ZIP). And rerun the make command. Hope it solves your issue.

**Comment by Racater** [comment]
Thank you for the help. Rebooting (and thus clearing the tmp folder) fixed the issue.
The issue was probably created by launching the script without a password the first time.

**Comment by leinardi** [comment]
Hey, thank you both for reporting the issue and investigating it.

I don't think that the issue was appending the file, what I think it happened is that the first time the script was launched, the ZIP archive was not downloaded correctly and and invalid file was left inside `/tmp/`.
When the script was relaunched, the download task checks if the file already exists to avoid re-downloading it (`creates: "/tmp/{{ product | replace(' ', '_') }}_{{ pkgver }}.zip"`) and this probably caused the issue.

A possible fix could be to validate existing archives and removing them if invalid, so that they will be re-downloaded (code not tested):
```yaml
- name: Validate existing DaVinci Resolve ZIP archive
  command: "unzip -t /tmp/{{ product | replace(' ', '_') }}_{{ pkgver }}.zip"
  register: zip_test
  failed_when: zip_test.rc != 0
  ignore_errors: true  # Ensure we proceed to deletion if this fails

- name: Remove invalid ZIP archive
  file:
    path: "/tmp/{{ product | replace(' ', '_') }}_{{ pkgver }}.zip"
    state: absent
  when: zip_test.failed  # Delete only if the validation failed
```
